<?php

namespace Database\Seeders;

use App\Models\Teaching;
use App\Models\Year;
use App\Models\Semester;
use App\Models\Trimester;
use Illuminate\Database\Seeder;

class TeachingSeeder extends Seeder
{
    public function run(): void
    {
        $teachings = [
            [
                'title' => 'SAÉ 1.01 Implémentation d\'un besoin client ',
                'apogee_code' => 'TIN01A1S',
                'tp_hours_initial' => 20.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 15.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 10.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAÉ 1.02 Comparaison d\'approches algorithmiques',
                'apogee_code' => 'TIN01A2S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 15.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 21.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAÉ 1.03 Installation d\'un poste pour le développement ',
                'apogee_code' => 'TIN01A3S',
                'tp_hours_initial' => 20.00,
                'tp_hours_continued' => 15.00,
                'td_hours_initial' => 20.00,
                'td_hours_continued' => 15.00,
                'cm_hours_initial' => 25.00,
                'cm_hours_continued' => 20.00,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],

            [
                'title' => 'SAÉ 1.04 Création d\'une base de données',
                'apogee_code' => 'TIN01A4S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAÉ 1.05 Recueil de besoins',
                'apogee_code' => 'TIN01A5S',
                'tp_hours_initial' => 10.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 15.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 10.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAÉ 1.06 Découverte de l\'environnement économique et écologique ',
                'apogee_code' => 'TIN01A6S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'Portfolio',
                'apogee_code' => 'TIN01A1P',
                'tp_hours_initial' => 20.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 15.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 10.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R1.01 Initiation au développement',
                'apogee_code' => 'TIN01A1M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R1.02 Développement d\'interfaces web',
                'apogee_code' => 'TIN01A2M',
                'tp_hours_initial' => 10.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 15.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 10.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R1.03 Introduction à l\'architecture des ordinateurs',
                'apogee_code' => 'TIN01A3M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R1.04 Introduction aux systèmes d\'exploitation et à leur fonctionnement',
                'apogee_code' => 'TIN01A4M',
                'tp_hours_initial' => 20.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 15.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 10.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R1.05 Introduction aux bases de données et SQL',
                'apogee_code' => 'TIN01A5M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R1.06 Mathématiques discrètes',
                'apogee_code' => 'TIN01A6M',
                'tp_hours_initial' => 10.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 15.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 10.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R1.07 Outils mathématiques fondamentaux',
                'apogee_code' => 'TIN01A7M',
                'tp_hours_initial' => 20.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 15.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 10.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R1.08 Introduction à la gestion des organisations',
                'apogee_code' => 'TIN01A8M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R1.09 Introduction à l\'économie durable et numérique',
                'apogee_code' => 'TIN01A9M',
                'tp_hours_initial' => 10.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 15.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 10.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R1.10 Anglais',
                'apogee_code' => 'TIN01AAM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R1.11 Bases de la communication',
                'apogee_code' => 'TIN01ABM',
                'tp_hours_initial' => 20.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 15.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 10.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R1.08 Introduction à la gestion des organisations',
                'apogee_code' => 'TIN01A8M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R1.09 Introduction à l\'économie durable et numérique',
                'apogee_code' => 'TIN01A9M',
                'tp_hours_initial' => 10.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 15.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 10.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R1.10 Anglais',
                'apogee_code' => 'TIN01AAM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R1.11 Bases de la communication',
                'apogee_code' => 'TIN01ABM',
                'tp_hours_initial' => 20.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 15.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 10.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R1.12 Projet Personnel et Professionnel',
                'apogee_code' => 'TIN01ACM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAÉ 2.01 Développement d\'une application',
                'apogee_code' => 'TIN02A1S',
                'tp_hours_initial' => 10.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 15.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 10.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAÉ 2.02 Exploration algorithmique d\'un problème',
                'apogee_code' => 'TIN02A2S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAÉ 2.03 Installation de services réseau',
                'apogee_code' => 'TIN02A3S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAÉ 2.04 Exploitation d\'une base de données',
                'apogee_code' => 'TIN02A4S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAÉ 2.05 Gestion d\'un projet',
                'apogee_code' => 'TIN02A5S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAÉ 2.06 Organisation d\'un travail d\'équipe',
                'apogee_code' => 'TIN02A6S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'Portfolio',
                'apogee_code' => 'TIN02A1P',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.01 Développement orienté objets',
                'apogee_code' => 'TIN02A1M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.02 Développement d\'applications avec IHM',
                'apogee_code' => 'TIN02A2M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.03 Qualité de développement',
                'apogee_code' => 'TIN02A3M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.04 Communication et fonctionnement bas niveau',
                'apogee_code' => 'TIN02A4M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.05 Introduction aux services réseaux',
                'apogee_code' => 'TIN02A5M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.06 Exploitation d\'une base de données',
                'apogee_code' => 'TIN02A6M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.07 Graphes',
                'apogee_code' => 'TIN02A7M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.08 Outils numériques pour les statistiques descriptives',
                'apogee_code' => 'TIN02A8M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.09 Méthodes numériques',
                'apogee_code' => 'TIN02A9M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.10 Introduction à la gestion des systèmes d\'information',
                'apogee_code' => 'TIN02AAM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R1.12 Projet Personnel et Professionnel',
                'apogee_code' => 'TIN01ACM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 1,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAÉ 2.01 Développement d\'une application',
                'apogee_code' => 'TIN02A1S',
                'tp_hours_initial' => 10.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 15.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAÉ 2.02 Exploration algorithmique d\'un problème',
                'apogee_code' => 'TIN02A2S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAÉ 2.03 Installation de services réseau',
                'apogee_code' => 'TIN02A3S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAÉ 2.04 Exploitation d\'une base de données',
                'apogee_code' => 'TIN02A4S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAÉ 2.05 Gestion d\'un projet',
                'apogee_code' => 'TIN02A5S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAÉ 2.06 Organisation d\'un travail d\'équipe',
                'apogee_code' => 'TIN02A6S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'Portfolio',
                'apogee_code' => 'TIN02A1P',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.01 Développement orienté objets',
                'apogee_code' => 'TIN02A1M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.02 Développement d\'applications avec IHM',
                'apogee_code' => 'TIN02A2M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.03 Qualité de développement',
                'apogee_code' => 'TIN02A3M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.04 Communication et fonctionnement bas niveau',
                'apogee_code' => 'TIN02A4M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.05 Introduction aux services réseaux',
                'apogee_code' => 'TIN02A5M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.06 Exploitation d\'une base de données',
                'apogee_code' => 'TIN02A6M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.07 Graphes',
                'apogee_code' => 'TIN02A7M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.08 Outils numériques pour les statistiques descriptives',
                'apogee_code' => 'TIN02A8M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.09 Méthodes numériques',
                'apogee_code' => 'TIN02A9M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.10 Introduction à la gestion des systèmes d\'information',
                'apogee_code' => 'TIN02AAM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.11 Introduction au droit',
                'apogee_code' => 'TIN02ABM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.12 Anglais',
                'apogee_code' => 'TIN02ACM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.13 Communication technique',
                'apogee_code' => 'TIN02ADM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R2.14 Projet Personnel et Professionnel',
                'apogee_code' => 'TIN02AEM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAE 3.01 Développement d’une application',
                'apogee_code' => 'TIN13A1S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 3,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'Portfolio',
                'apogee_code' => 'TIN13A1P',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 3,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R3.01 Développement web',
                'apogee_code' => 'TIN13A1M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 3,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R3.02 Développement efficace ',
                'apogee_code' => 'TIN13A2M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 3,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R3.03 Analyse',
                'apogee_code' => 'TIN13A3M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 3,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R3.04 Qualité et développement',
                'apogee_code' => 'TIN13A4M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 3,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R3.05 Programmation système',
                'apogee_code' => 'TIN13A5M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 3,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R3.06 Architecture des réseaux ',
                'apogee_code' => 'TIN13A6M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 3,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R3.07 SQL dans un langage de programmation',
                'apogee_code' => 'TIN13A7M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 3,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R3.08 Probabilités',
                'apogee_code' => 'TIN13A8M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 3,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R3.09 Cryptographie et sécurité',
                'apogee_code' => 'TIN13A9M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 3,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R3.10 Management des systèmes d’information',
                'apogee_code' => 'TIN13AAM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 3,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R3.11 Droit des contrats et du numérique ',
                'apogee_code' => 'TIN13ABM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 3,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R3.12 Anglais',
                'apogee_code' => 'TIN13ACM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 2,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R3.13 Communication professionnelle',
                'apogee_code' => 'TIN13ADM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 3,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R3.14 Projet personnel et professionnel',
                'apogee_code' => 'TIN13AEM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 3,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAE 4.01 Développement d\'une application complexe',
                'apogee_code' => 'TIN14A1S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 4,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'Stage',
                'apogee_code' => 'TIN14A2S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 4,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'Portfolio',
                'apogee_code' => 'TIN14A1P',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 4,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R4.01 Architecture logicielle',
                'apogee_code' => 'TIN14A1M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 4,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R4.02 Qualité et développement',
                'apogee_code' => 'TIN14A2M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 4,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R4.03 Qualité au-delà du relationnel',
                'apogee_code' => 'TIN14A3M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 4,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R4.04 Méthode d\'optimisation',
                'apogee_code' => 'TIN14A4M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 4,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R4.05 Anglais',
                'apogee_code' => 'TIN14A5M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 4,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R4.06 Communication interne',
                'apogee_code' => 'TIN14A6M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 4,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R4.07 Projet personnel et professionnel',
                'apogee_code' => 'TIN14A7M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 4,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R4.08 Virtualisation',
                'apogee_code' => 'TIN14A8M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 4,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R4.09 Management avancé des systèmes d’information',
                'apogee_code' => 'TIN14A9M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 4,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R4.10 Complément web',
                'apogee_code' => 'TIN14AAM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 4,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R4.11 Développement pour applications mobiles',
                'apogee_code' => 'TIN14ABM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 4,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R4.12 Automates et Langages',
                'apogee_code' => 'TIN14ACM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 4,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAÉ 5.Real.01 | Développement avancé',
                'apogee_code' => 'TIN15A1S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 5,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'Portfolio',
                'apogee_code' => 'TIN15A1P',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 5,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R5.01 | Initiation au management d\'une équipe de projet informatique',
                'apogee_code' => 'TIN15A1M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 5,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R5.02 | Projet personnel et professionnel',
                'apogee_code' => 'TIN15A2M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 5,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R5.03 | Politique de communication',
                'apogee_code' => 'TIN15A3M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 5,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R5.Real.04 | Qualité algorithmique',
                'apogee_code' => 'TIN15A4M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 5,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R5.Real.05 | Programmation avancée',
                'apogee_code' => 'TIN15A5M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 5,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R5.Real.06 | Sensibilisation à la programmation multimédia',
                'apogee_code' => 'TIN15A6M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 5,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R5.Real.07 | Automatisation de la chaîne de production',
                'apogee_code' => 'TIN15A7M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 5,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R5.Real.08 | Qualité de développement',
                'apogee_code' => 'TIN15A8M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 5,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R5.Real.09 | Virtualisation avancée',
                'apogee_code' => 'TIN15A9M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 5,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R5.Real.10 | Nouveaux paradigmes de base de données',
                'apogee_code' => 'TIN15AAM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 5,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R5.Real.11 | Méthodes d\'optimisation pour l\'aide à la décision',
                'apogee_code' => 'TIN15ABM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 5,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R5.Real.12 | Modélisations mathématiques',
                'apogee_code' => 'TIN15ACM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 5,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R5.Real.13 | Économie durable et numérique',
                'apogee_code' => 'TIN15ADM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 5,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R5.Real.14 | Anglais',
                'apogee_code' => 'TIN15AEM',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 5,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'SAÉ 6.Real.01 | Évolution d\'une application existante',
                'apogee_code' => 'TIN16A1S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 6,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'Stage',
                'apogee_code' => 'TIN16A2S',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 6,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'Portfolio',
                'apogee_code' => 'TIN16A1P',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 6,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R6.01 | Initiation à l\'entrepreneuriat',
                'apogee_code' => 'TIN16A1M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 6,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R6.02 | Droit du numérique et de la propriété intellectuelle',
                'apogee_code' => 'TIN16A2M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 6,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R6.03 | Communication : organisation et diffusion de l\'information',
                'apogee_code' => 'TIN16A3M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 6,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R6.04 | Projet personnel et professionnel',
                'apogee_code' => 'TIN16A4M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 6,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R6.Real.05 | Développement avancée',
                'apogee_code' => 'TIN16A5M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 6,
                'trimester_id' => null,
                'year_id' => 1
            ],
            [
                'title' => 'R6.Real.06 | Maintenance applicative',
                'apogee_code' => 'TIN16A6M',
                'tp_hours_initial' => 15.00,
                'tp_hours_continued' => null,
                'td_hours_initial' => 10.00,
                'td_hours_continued' => null,
                'cm_hours_initial' => 15.00,
                'cm_hours_continued' => null,
                'semester_id' => 6,
                'trimester_id' => null,
                'year_id' => 1
            ],


        ];

        foreach ($teachings as $teaching) {
            Teaching::create($teaching);
        }
    }
}
